site_name: 钛极OS(TiJOS)应用开发指南
pages:
- 目录 : index.md
- TiJOS应用开发环境搭建 : tijos_runtime_guide/tijos_application_devsuite_setup.md
- Ti-Dev Manager设备管理器 : tijos_runtime_guide/tijos_device_manager.md
- Ti-Dev Studio开发工具 : tijos_runtime_guide/tijos_dev_studio.md
- 第一个TiJOS应用 : tijos_runtime_guide/tijos_helloworld.md
- TiJOS应用参考例程 :  tijos_runtime_guide/tijos_examples.md
- TiJOS JDK Java标准库支持 : tijos_runtime_guide/tijos_java_standard_support.md
- TiJOS Hardware Access JDK : tijos_runtime_guide/tijos_runtime_sdk.md
- TiJOS设备总线支持 : tijos_runtime_guide/tijos.runtime.deviceaccess.md
- TiADC - 模数转换器 : tijos_runtime_guide/tijos.runtime.deviceaccess.TiADC.md
- TiGPIO - 通用输入/输出 : tijos_runtime_guide/tijos.runtime.deviceaccess.TiGPIO.md
- TiI2CMaster - 双向二线制同步串行总线 : tijos_runtime_guide/tijos.runtime.deviceaccess.TiI2CMaster.md
- TiOWMaster - 单总线 : tijos_runtime_guide/tijos.runtime.deviceaccess.TiOWMaster.md
- TiPWM - 脉冲宽度调制发生器 : tijos_runtime_guide/tijos.runtime.deviceaccess.TiPWM.md
- TiSPIMaster - 串行外设接口 : tijos_runtime_guide/tijos.runtime.deviceaccess.TiSPIMaster.md
- TiUART - 通用异步收发传输器 : tijos_runtime_guide/tijos.runtime.deviceaccess.TiUART.md
- TiJOS传感器支持 : tijos_runtime_guide/tijos.runtime.sensor.md
- 按键 : tijos_runtime_guide/tijos.runtime.sensor.button.md
- 测距模块 : tijos_runtime_guide/tijos.runtime.sensor.distance.md
- 气体传感器 : tijos_runtime_guide/tijos.runtime.sensor.gas.md
- 温湿度传感器 : tijos_runtime_guide/tijos.runtime.sensor.humiture.md
- 红外线传感器 : tijos_runtime_guide/tijos.runtime.sensor.infrared.md
- 蜂鸣器 : tijos_runtime_guide/tijos.runtime.transducer.buzzer.md
- LED/OLED显示 : tijos_runtime_guide/tijos.runtime.transducer.led.md
- 继电器 : tijos_runtime_guide/tijos.runtime.transducer.relay.md
- TiJOS网络应用开发指南 : tijos_runtime_guide/tijos_net.md
- MQTT 客户端 : tijos_runtime_guide/tijos.runtime.net.mqtt.md
- 网络时间协议客户端 : tijos_runtime_guide/tijos.runtime.net.ntp.md
- 网络管理中心 : tijos_runtime_guide/tijos.runtime.networkcenter.md
- 在线应用升级 : tijos_runtime_guide/tijos.runtime.ota.md
- TiJOS常用工具类 : tijos_runtime_guide/tijos.util.md
- BASE64编码 : tijos_runtime_guide/tijos.util.base64.md
- CRC校验码 : tijos_runtime_guide/tijos.util.crc.md
- JSON : tijos_runtime_guide/tijos.util.json.md
- 日志输出 : tijos_runtime_guide/tijos.util.logging.md
- 硬件事件中心 : tijos_runtime_guide/tijos.runtime.eventcenter.md
- 平台设置 : tijos_runtime_guide/tijos.runtime.platform.md


theme: readthedocs