site_name: 钛极OS(TiJOS)应用开发指南
pages:
- 目录 : index.md
- TiJOS应用开发环境搭建 : tijos_framework_guide/tijos_application_devsuite_setup.md
- Ti-Dev Manager设备管理器 : tijos_framework_guide/tijos_device_manager.md
- TiJOS系统工作模式: tijos_framework_guide/tijos_workingmode.md
- Ti-Dev Studio开发工具 : tijos_framework_guide/tijos_dev_studio.md
- 第一个TiJOS应用 : tijos_framework_guide/tijos_helloworld.md
- TiJOS应用参考例程 :  tijos_framework_guide/tijos_examples.md
- TiJOS Java标准库支持 : tijos_framework_guide/tijos_java_standard_support.md
- TiJOS Framework : tijos_framework_guide/tijos_framework_sdk.md
- TiJOS设备总线支持:
    - 概述 : tijos_framework_guide/tijos.framework.devicecenter.md
    - TiADC - 模数转换器 : tijos_framework_guide/tijos.framework.devicecenter.TiADC.md
    - TiGPIO - 通用输入/输出 : tijos_framework_guide/tijos.framework.devicecenter.TiGPIO.md
    - TiI2CMaster - 双向二线制同步串行总线 : tijos_framework_guide/tijos.framework.devicecenter.TiI2CMaster.md
    - TiOWMaster - 单总线 : tijos_framework_guide/tijos.framework.devicecenter.TiOWMaster.md
    - TiPWM - 脉冲宽度调制发生器 : tijos_framework_guide/tijos.framework.devicecenter.TiPWM.md
    - TiSPIMaster - 串行外设接口 : tijos_framework_guide/tijos.framework.devicecenter.TiSPIMaster.md
    - TiUART - 通用异步收发传输器 : tijos_framework_guide/tijos.framework.devicecenter.TiUART.md
- TiJOS传感器应用开发指南: tijos_framework_guide/tijos_sensor_application_guide.md
- TiJOS传感器支持:
    - 概述: tijos_framework_guide/tijos.framework.sensor.md
    - 按键: tijos_framework_guide/tijos.framework.sensor.button.md
    - 测距模块 : tijos_framework_guide/tijos.framework.sensor.distance.md
    - 气体传感器 : tijos_framework_guide/tijos.framework.sensor.gas.md
    - 温湿度传感器 : tijos_framework_guide/tijos.framework.sensor.humiture.md
    - 红外线传感器 : tijos_framework_guide/tijos.framework.sensor.infrared.md
    - 蜂鸣器 : tijos_framework_guide/tijos.framework.transducer.buzzer.md
    - LED/OLED显示 : tijos_framework_guide/tijos.framework.transducer.led.md
    - 继电器 : tijos_framework_guide/tijos.framework.transducer.relay.md
    - 通用传感器 : tijos_framework_guide/tijos.framework.sensor.general.md
- TiJOS网络应用开发指南:  
    - 概述 : tijos_framework_guide/tijos_net.md
    - MQTT 客户端 : tijos_framework_guide/tijos.framework.net.mqtt.md
    - 网络时间协议客户端 : tijos_framework_guide/tijos.framework.net.ntp.md
    - 网络管理中心 : tijos_framework_guide/tijos.framework.networkcenter.md
- TiJOS常用工具类:
    - 概述 : tijos_framework_guide/tijos.util.md
    - BASE64编码 : tijos_framework_guide/tijos.util.base64.md
    - CRC校验码 : tijos_framework_guide/tijos.util.crc.md
    - JSON : tijos_framework_guide/tijos.util.json.md
    - 日志输出 : tijos_framework_guide/tijos.util.logging.md
- 在线应用升级 : tijos_framework_guide/tijos.framework.ota.md
- 硬件事件中心 : tijos_framework_guide/tijos.framework.eventcenter.md
- 平台设置 : tijos_framework_guide/tijos.framework.platform.md
- 更多在线资源 : resources.md

# Repository
repo_name: '钛极OS(TiJOS)文档中心'
repo_url: 'http://www.tijos.net/docs#gitlab'


# Copyright
copyright: 'Copyright &copy; 2017 - 2020 TiCloud Technology'

# Configuration
theme:
  name: 'material'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/TiJOSteam'
      
      # Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      
